name: fcm_api

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.2.3
  built_value: ^7.1.0
  logging: ^0.11.4
  googleapis_auth: ^0.2.12
  googleapis: ^0.55.0



dev_dependencies:
  build_runner:
  built_value_generator: ^7.1.0