name: fcm_api

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.3.0
  built_value: ^8.0.5
  logging: ^1.0.1
  googleapis_auth: ^1.1.0
  googleapis: ^2.0.0



dev_dependencies:
  build_runner:
  built_value_generator: ^8.0.5